name: Build
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  write-all

jobs:
  build-mac:
    name: Build for macOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build for macOS (Universal)
        shell: bash
        run: |
          xcodebuild -project 'PhotosProcessor.xcodeproj' -scheme 'PhotosProcessor' -configuration 'Release' -destination 'platform=macOS' build  -derivedDataPath 'build'
      - name: Create DMG
        shell: bash
        run: |
          hdiutil create -volname "PhotosProcessor" -srcfolder "build/Build/Products/Release/PhotosProcessor.app" -ov -format UDZO "PhotosProcessor.dmg"
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PhotosProcessor.dmg
          path: PhotosProcessor.dmg
      - name: Upload DMG to GitHub Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: PhotosProcessor.dmg
          asset_name: PhotosProcessor.dmg
          asset_content_type: application/x-apple-diskimage